apiVersion: v1
kind: Secret
metadata:
  name: postit-db
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: REPLACE_ME_DEV_MARIADB_ROOT_PASSWORD
  MARIADB_PASSWORD: REPLACE_ME_DEV_MARIADB_PASSWORD
  MARIADB_USER: REPLACE_ME_DEV_MARIADB_USER
  MARIADB_DATABASE: REPLACE_ME_DEV_MARIADB_DATABASE
