apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postit-mariadb-data
  labels:
    app.kubernetes.io/name: postit-mariadb
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: REPLACE_ME_STORAGE_CLASS
  resources:
    requests:
      storage: REPLACE_ME_STORAGE_SIZE
